name: Build and Deploy Static

on:
  push:
    branches:
      - main

jobs:
  BuildandDeploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write  
      id-token: write 

    environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend/elcocinillas/

      - name: Build Vue App
        run: npm run build
        working-directory: ./frontend/elcocinillas/

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: './frontend/elcocinillas/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
